### ISSUE TITLE
[th175] 1.15版游戏崩溃

### ISSUE THREAD

**Issue by xitieshiz2** [thpatch-zh/script_zh-hans#22]
todo: 參考script_latin修正该问题
log: [https://gist.github.com/xitieshiz2/ec95a083c162359d8c0730f3b0ad4977](https://gist.github.com/xitieshiz2/ec95a083c162359d8c0730f3b0ad4977)

**Comment by Yanstory** [comment]
可能需要将所有的nut文件覆盖改为thcrap jdiff方式

**Comment by xitieshiz2** [comment]
> 可能需要将所有的nut文件覆盖改为thcrap jdiff方式

我看了文件树之后也是这么想的，可惜我不太会用135tk的act-nut-tool，还是得麻烦你了

**Comment by RetroCyber** [comment]
现已修复
